AllCops:
  Exclude:
    - spec/dummy/db/schema.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90
  Exclude:
    - liquidize.gemspec
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - lib/liquidize/model.rb

FrozenStringLiteralComment:
  Enabled: false
