language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/5.0.gemfile
      rvm: 2.0.0
    - gemfile: gemfiles/5.0.gemfile
      rvm: 2.1.0

env:
  - DB=sqlite

script:
  - cd spec/dummy/
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../../
  - bundle exec rspec spec/
